export type Mode = "artwork" | "performance" | "events" | "disabled";
export type ArtworkMode = "auto" | "center" | "lower" | "manual";
export type ArtworkSource = "hero" | "header" | "capsule";
export type PerformanceMetric = "cpu" | "gpu" | "mixed";
export type PerformanceSmoothing = "responsive" | "balanced" | "smooth";
export type MixedDirection = "same" | "mirrored";
export type TemperaturePalette = "thermal" | "classic" | "icefire" | "custom";
export type CountdownColour = "cyan" | "green" | "amber" | "violet" | "white";
export type RGB = [number, number, number];
export type WeatherCondition = "clear_day" | "clear_night" | "rain" | "cloud" | "breaks" | "breaks_night" | "snow" | "storm";
export interface WeatherLocation { name: string; country: string; latitude: number; longitude: number }

export interface PongStatus {
  active: boolean;
  session_id: number;
  phase: "idle" | "ready" | "rally" | "point" | "level" | "finished";
  mode: "" | "solo" | "duel";
  input_source: "touch" | "browser" | "steam";
  action_button: number;
  gamepad_indices: number[];
  scores: number[];
  lives: number;
  streak: number;
  returns: number;
  best_streak: number;
  level: number;
  winner: number;
  paused: boolean;
  pause_reason: string;
  feedback_seq: number;
  feedback_player: number;
  feedback_kind: string;
  led_write_ms: number | null;
  led_write_count: number;
  led_write_pending: boolean;
  vibration_enabled?: boolean;
  colors: RGB[];
}

export interface Status {
  version: string;
  pong: PongStatus;
  pong_vibration_enabled: boolean;
  available: boolean;
  active: boolean;
  owner: "Valve" | "SignalBar";
  provider: string;
  suspension_reason: string;
  error: string;
  mode: Mode;
  default_mode: Mode;
  display_override: "inherit" | "artwork" | "performance";
  performance_metric: PerformanceMetric;
  performance_smoothing: PerformanceSmoothing;
  performance_always: boolean;
  mixed_direction: MixedDirection;
  temperature_palette: TemperaturePalette;
  temperature_custom_cool: RGB;
  temperature_custom_middle: RGB;
  temperature_custom_hot: RGB;
  artwork_mode: ArtworkMode;
  artwork_manual_y: number;
  artwork_source: ArtworkSource;
  artwork_custom: boolean;
  artwork_default_mode: ArtworkMode;
  artwork_default_manual_y: number;
  artwork_default_source: ArtworkSource;
  cool_temp_c: number;
  hot_temp_c: number;
  reverse_led_order: boolean;
  parental_countdown_enabled: boolean;
  countdown_colour: CountdownColour;
  countdown_full_bar_minutes: 0 | 60 | 120 | 180 | 240;
  countdown_dark_edge_compensation: number;
  free_timer_minutes: number;
  events_enabled: boolean;
  event_notifications_enabled: boolean;
  event_achievements_enabled: boolean;
  event_screenshots_enabled: boolean;
  event_recording_enabled: boolean;
  recording_marker_isolation: boolean;
  event_notification_variant: string;
  event_achievement_variant: string;
  event_screenshot_variant: string;
  controller_battery_display: "off" | "home" | "game" | "everywhere";
  controller_charging_mode: "off" | "brief" | "continuous-home" | "continuous-everywhere";
  controller_charging_display: "off" | "home" | "everywhere";
  controller_alert_context: "off" | "home" | "game" | "both";
  controller_alerts_enabled: boolean;
  controller_connect_enabled: boolean;
  controller_low_enabled: boolean;
  controller_charging_enabled: boolean;
  controller_low_threshold: number;
  controller_connect_variant: string;
  controller_persistent_variant: string;
  controller_low_variant: string;
  controller_charging_variant: string;
  controller_duo_variant: string;
  controller_colour_normal: RGB;
  controller_colour_medium: RGB;
  controller_colour_low: RGB;
  controller_colour_charging: RGB;
  controller_gauge_brightness: number;
  weather_display: "off" | "home" | "game" | "everywhere";
  weather_location: WeatherLocation | null;
  weather_topbar_enabled: boolean;
  weather_temperature_unit: "celsius" | "fahrenheit";
  weather_brightness: number;
  weather_shadow_cutoff: number;
  weather_clear_day_variant: number;
  weather_clear_night_variant: number;
  weather_rain_variant: number;
  weather_cloud_variant: number;
  weather_breaks_variant: number;
  weather_breaks_night_variant: number;
  weather_snow_variant: number;
  weather_storm_variant: number;
  weather: {
    location: WeatherLocation | null;
    display: Status["weather_display"];
    phase: "off" | "waiting" | "loading" | "ready" | "error";
    error: string;
    temperature_c: number | null;
    condition: WeatherCondition | null;
    is_day: boolean | null;
    weather_code: number | null;
    observed_at: string;
    age_s: number | null;
    preview_active: boolean;
    preview_remaining_s: number;
    colors: RGB[];
    active_here: boolean;
  };
  controllers: {
    controllers: { id: string; name: string; percent: number | null; level: number | null; charging: boolean | null }[];
    active: boolean;
    kind: string;
    variant: string;
    colors: RGB[];
    persistent_available: boolean;
    charging_active: boolean;
  };
  events: {
    active: boolean;
    kind: string;
    variant: string;
    recording: boolean;
    queued: number;
    colors: RGB[];
  };
  game: { appid: number; title: string };
  performance: {
    sample_age_s: number | null;
    error: string;
    gpu_load: number | null;
    gpu_temperature: number | null;
    cpu_load: number | null;
    cpu_temperature: number | null;
    logical_lit: number;
    physical_lit: number;
  };
  artwork: { sample_y?: number; filename?: string; colors?: RGB[] };
  countdown: {
    active: boolean;
    source: "" | "parental" | "free" | "preview";
    label: string;
    remaining_seconds: number;
    total_seconds: number;
    scale_seconds: number;
    alerting: boolean;
    logical_lit: number;
    physical_lit: number;
    colors: RGB[];
  };
  debug: {
    led_path: string;
    last_write: number;
    last_write_age_s: number | null;
    writes: number;
    last_external: number;
    last_external_age_s: number | null;
    cooldown_remaining: number;
    stable_remaining: number;
    guard_state: "ready" | "blocked";
    guard_reason: string;
    reverse_led_order: boolean;
    appid: number;
    game_detection_source: string;
    game_sync_ms: number | null;
    parental_callback_state: "idle" | "disabled" | "waiting" | "received";
    parental_callback_delay_ms: number | null;
    parental_wait_s: number | null;
    controller_callback_source: string;
    controller_last_update_age_s: number | null;
    controller_telemetry: import("./controller_monitor").ControllerTelemetry;
  };
}

export interface ArtworkPayload {
  found: boolean;
  appid: number;
  mime?: string;
  filename?: string;
  fingerprint?: string;
  data_uri?: string;
  cached?: boolean;
  source?: ArtworkSource;
  source_label?: string;
}
